"""Resolve the runtime dependencies for linux/amd64 and write a hash-pinned lockfile.

There was no lockfile of any kind, so every transitive floated. Rule 13 wants
pinned and verified versions, and a container image is the one artefact where
that matters most: it is what ships, and "it worked when I built it" is not a
property anyone can re-derive later.

**Why this cannot just be `pip freeze`.** The development venv is macOS
arm64 and Cloud Run runs linux/amd64 only, so a freeze here records wheels
that cannot be installed there -- ADR-001 already documents two of them
(`ruff`, `sqlite-vec`) as platform-locked despite a `py3` prefix. This script
asks pip to resolve *as if* it were the target platform instead, using
`--dry-run --report`, which reports the resolution without installing it.

**Why the platform list is long.** `--platform` matches wheel tags by exact
string, not by compatibility, so a single `manylinux_2_28_x86_64` silently
excludes every wheel tagged `manylinux_2_17_x86_64` -- which is most of them.
The first run of this failed as `ResolutionImpossible` on `pydantic-core` for
exactly that reason, and the failure named the package rather than the cause,
which is why the list below is written out with this note beside it.

**Runtime only, deliberately.** The image installs no dev dependencies, and
CI deliberately keeps resolving transitives freely: that is how the
`langgraph-sdk` drift behind Phase 13's first red build was noticed at all.
Pinning CI too would trade a working early-warning signal for a reproducibility
it does not need. Different jobs, different needs -- the image is what ships,
so the image is what is pinned.

Run from `backend/`:
    ./.venv/bin/python scripts/lock_linux_deps.py
"""

import json
import subprocess
import sys
import tomllib
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
PYPROJECT = BACKEND / "pyproject.toml"
LOCKFILE = BACKEND / "requirements.lock"

PYTHON_VERSION = "3.14"

# Exact wheel-tag strings, not a compatibility range -- see the module
# docstring. Ordered oldest-first because an older manylinux wheel runs on a
# newer glibc and is therefore the safer match when several exist.
PLATFORMS = (
    "manylinux1_x86_64",
    "manylinux_2_5_x86_64",
    "manylinux2014_x86_64",
    "manylinux_2_17_x86_64",
    "manylinux_2_28_x86_64",
    "manylinux_2_34_x86_64",
)


def runtime_requirements() -> list[str]:
    """The `[project].dependencies` list, verbatim and pinned as written."""
    with PYPROJECT.open("rb") as handle:
        return list(tomllib.load(handle)["project"]["dependencies"])


def resolve(requirements: list[str], report: Path) -> None:
    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--dry-run",
        "--ignore-installed",
        "--only-binary=:all:",
        "--python-version",
        PYTHON_VERSION,
        "--implementation",
        "cp",
        "--report",
        str(report),
    ]
    for platform in PLATFORMS:
        command += ["--platform", platform]
    command += requirements
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL)


def render(report: Path, requirements: list[str]) -> str:
    entries = json.loads(report.read_text())["install"]
    rows: list[str] = []
    for entry in sorted(entries, key=lambda e: e["metadata"]["name"].lower()):
        name = entry["metadata"]["name"]
        version = entry["metadata"]["version"]
        digest = entry["download_info"]["archive_info"]["hashes"]["sha256"]
        wheel = entry["download_info"]["url"].rsplit("/", 1)[-1]
        rows.append(f"# {wheel}\n{name}=={version} \\\n    --hash=sha256:{digest}")

    header = [
        "# Generated by scripts/lock_linux_deps.py -- do not edit by hand.",
        "#",
        f"# Resolved for linux/amd64, CPython {PYTHON_VERSION}, wheels only.",
        "# Installed with --require-hashes, so every line here is verified at",
        "# build time and an unpinned transitive cannot slip in.",
        "#",
        "# Runtime dependencies only. Regenerate after editing",
        "# [project].dependencies in pyproject.toml, which currently declares:",
        *(f"#   {r}" for r in requirements),
        "",
    ]
    return "\n".join(header) + "\n".join(rows) + "\n"


if __name__ == "__main__":
    requirements = runtime_requirements()
    report = BACKEND / ".lock-report.json"
    try:
        resolve(requirements, report)
        LOCKFILE.write_text(render(report, requirements))
    finally:
        report.unlink(missing_ok=True)
    total = LOCKFILE.read_text().count("--hash=sha256:")
    print(f"wrote {LOCKFILE.relative_to(BACKEND)} — {total} pinned distributions")
