/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/agent/resume": {
    /** Resume */
    post: operations["resume_api_agent_resume_post"];
  };
  "/api/agent/start": {
    /** Start */
    post: operations["start_api_agent_start_post"];
  };
  "/api/agent/status/{thread_id}": {
    /**
     * Get Status
     * @description The one response shape, in every state.
     *
     * A thread nobody started is a **404** rather than an empty snapshot:
     * measured against the pinned LangGraph, `aget_state` answers for an unknown
     * id with a perfectly ordinary snapshot, so an endpoint that did not check
     * would return 200 and a blank report for any string a client sent.
     */
    get: operations["get_status_api_agent_status__thread_id__get"];
  };
  "/api/health": {
    /**
     * Health
     * @description Liveness, local-store readiness, and model-provider configuration.
     *
     * `status` is derived from `checks` by `_derive_status` and is never
     * asserted independently of them. It previously was: the endpoint returned
     * a hardcoded `"ok"` alongside whatever the checks happened to say, so a
     * 200 with `"ok"` was demonstrated while both store checks were false --
     * and the frontend rendered that as a green tick. A health endpoint that
     * cannot be wrong about its own checks is the whole point of this route.
     *
     * Every check is a cheap local read: two filesystem stats and one look at
     * already-loaded settings. Nothing here is reported as unknown because
     * nothing here is expensive enough to need to be. In particular this
     * deliberately does **not** open the Chroma store, connect to the
     * checkpointer database, or call the model provider -- a health probe must not cost
     * money or inherit third-party latency, so what it reports is the
     * readiness of the store *locations* and the presence of a key, which is
     * exactly what the field names say and no more.
     *
     * `llm_configured` counts toward `status` like any other check. A
     * missing key means the agent cannot do its job, so reporting `"ok"`
     * without one would be the same class of false claim in a smaller font.
     */
    get: operations["health_api_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AffectedFile */
    AffectedFile: {
      /** Commit Count */
      commit_count?: number | null;
      /**
       * Is Test
       * @default false
       */
      is_test?: boolean;
      /** Last Modified */
      last_modified?: string | null;
      /** Path */
      path: string;
      /**
       * Symbols
       * @description The distinct symbols used in this file, sorted.
       *
       * Derived, never stored -- CLAUDE.md rule 21, and the same argument
       * `SymbolInventory.by_symbol` makes just above. As a field it could
       * disagree with `usage_sites`, which is the one thing that must never
       * happen here: `usage_sites` carries the file and line the report
       * cites, and `symbols` is what the corpus is queried with, so drift
       * between them means citing evidence for a symbol nobody uses.
       *
       * `@computed_field` rather than a bare property so it still appears in
       * `model_dump()`, keeping the serialised shape it had as a field. It
       * recomputes on access rather than caching: the input is a frozen
       * tuple, so there is nothing to invalidate and nothing to go stale.
       */
      symbols: readonly string[];
      /** Usage Sites */
      usage_sites: components["schemas"]["UsageSite"][];
    };
    /**
     * ApiError
     * @description One error, as a client is allowed to see it. See the module docstring.
     */
    ApiError: {
      code: components["schemas"]["ErrorCode"];
      /** Message */
      message: string;
      /** Node */
      node?: string | null;
      /**
       * Retryable
       * @default false
       */
      retryable?: boolean;
    };
    /**
     * BreakingChange
     * @description A documented change. `source` is required: no citation, no change.
     */
    BreakingChange: {
      /** Affected Symbols */
      affected_symbols: string[];
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** New Form */
      new_form?: string | null;
      /** Old Form */
      old_form?: string | null;
      severity: components["schemas"]["Severity"];
      source: components["schemas"]["SourceRef"];
      /** Title */
      title: string;
    };
    /** CommitRecord */
    CommitRecord: {
      /**
       * Files
       * @default []
       */
      files?: string[];
      /** Sha */
      sha: string;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
    };
    /**
     * Confidence
     * @description Confidence in a detected usage site or symbol.
     * @enum {string}
     */
    Confidence: "low" | "medium" | "high";
    /**
     * ConfidenceCeiling
     * @description One reason this analysis cannot be as confident as its factors suggest.
     *
     * Carries its reason as a user-facing sentence rather than a code, because
     * the ceiling is the answer to a question the reader is actually asking --
     * "why does this say 30%?" -- and a code would need a lookup table
     * somewhere else that could disagree with the number beside it.
     */
    ConfidenceCeiling: {
      /** Ceiling */
      ceiling: number;
      /** Reason */
      reason: string;
    };
    /**
     * ConstraintEvidence
     * @description A constraint the user stated, cited as the thing it actually is.
     *
     * Added in Phase 6, and the reason is specific: `constraint_pressure` is one
     * of spec 8.1's seven risk factors, `RiskFactor.evidence` has
     * `min_length=1`, and a constraint is not in the repository or in the
     * corpus. The three ways out were to cite an unrelated repository line
     * (a fabricated citation, and exactly what this package exists to prevent),
     * to exempt one factor from the evidence rule (a hole the next factor walks
     * through), or to say what the evidence really is. This is the third.
     *
     * It resolves, which is what makes it evidence rather than a label: `field`
     * names a real field of `UserConstraints` and `value` is that field's value
     * as the run received it, so a validator can check the citation against the
     * run's own inputs the same way a `RepoEvidence` is checked against the
     * analysis record.
     */
    ConstraintEvidence: {
      /** Field */
      field: string;
      /**
       * Kind
       * @default constraint
       * @constant
       */
      kind?: "constraint";
      /** Value */
      value: string;
    };
    /**
     * DecisionApplication
     * @description How one human decision changed the plan that followed it.
     *
     * Spec 8.3 makes the human's influence structural rather than claimed: a
     * plan that carries a decision must say what the decision *did*, in a
     * sentence, and `validate_plan`'s ninth check refuses a plan where a
     * decision exists and this list is empty. "The human's answer affected the
     * output" stops being an assertion in a README and becomes a validation
     * failure when it is not true.
     */
    DecisionApplication: {
      /** Decision Id */
      decision_id: string;
      /** How It Changed The Plan */
      how_it_changed_the_plan: string;
    };
    /**
     * DecisionInput
     * @description A human's answer. Validated again inside the graph, deliberately.
     *
     * This model checks the *shape*; `human_review` checks that the option
     * exists on the question being asked, because only the graph knows which
     * question that is. Two layers, and the inner one is the one that matters --
     * it is reachable however the resume value arrives.
     */
    DecisionInput: {
      /** Question Id */
      question_id: string;
      /** Rationale */
      rationale?: string | null;
      /** Selected Option Id */
      selected_option_id: string;
    };
    /**
     * DecisionKind
     * @description The four questions this system is willing to put to a human.
     *
     * Spec 8.2 fixes the list, and fixing it is the design: an open-ended
     * "ask the user something" would degenerate into the ceremonial dialog the
     * brief's conditional edge exists to prevent. Each kind below has a
     * deterministic trigger -- a condition in the evidence, not a judgement call
     * -- so a run either has a real question or has none.
     * @enum {string}
     */
    DecisionKind: "strategy_choice" | "risk_acceptance" | "scope_tradeoff" | "discrepancy_resolution";
    /**
     * DecisionOption
     * @description One answer a human may give, with what it costs and what it commits to.
     */
    DecisionOption: {
      /** Consequences */
      consequences: string[];
      /** Downtime */
      downtime: boolean;
      effort: components["schemas"]["EffortLevel"];
      /** Id */
      id: string;
      /** Label */
      label: string;
      risk_level: components["schemas"]["RiskLevel"];
      /** Summary */
      summary: string;
      /** Supporting Evidence */
      supporting_evidence: (components["schemas"]["RepoEvidence"] | components["schemas"]["DocEvidence"] | components["schemas"]["ConstraintEvidence"])[];
    };
    /** DependencyInput */
    DependencyInput: {
      /** Current Version */
      current_version: string;
      /** Name */
      name: string;
      /** Target Version */
      target_version: string;
    };
    /**
     * DependencyRole
     * @enum {string}
     */
    DependencyRole: "direct" | "transitive_only";
    /** DependencySpec */
    DependencySpec: {
      /**
       * Canonical Name
       * @description PEP 503 normalised name. See `canonicalize_name` above for why.
       *
       * Derived, never stored (CLAUDE.md rule 21): a stored copy could
       * disagree with `name`.
       */
      canonical_name: string;
      /** Current Version */
      current_version: string;
      /**
       * Import Root
       * @description The top-level module name this distribution is expected to provide.
       *
       * A GUESS, and the honest name for it is a guess: the mapping from
       * distribution name to import name lives in installed package metadata,
       * which a static analysis of a cloned repository does not have.
       * `pydantic` -> `pydantic` is right; `python-dateutil` -> `dateutil` and
       * `PyYAML` -> `yaml` are the well-known cases where it is wrong.
       *
       * `services/analysis/analyzer.py` records an explicit confidence reducer
       * whenever this guess yields no candidate files, so a wrong guess reads
       * as "we could not find it" rather than as "this dependency is unused".
       */
      import_root: string;
      /** Name */
      name: string;
      /** Target Version */
      target_version: string;
    };
    /** DetectedVersion */
    DetectedVersion: {
      confidence: components["schemas"]["VersionConfidence"];
      role: components["schemas"]["DependencyRole"];
      source_manifest: components["schemas"]["Manifest"];
      /** Specifier */
      specifier: string | null;
      /** Value */
      value: string;
    };
    /**
     * DocEvidence
     * @description A specific chunk of a corpus document.
     */
    DocEvidence: {
      /** Chunk Id */
      chunk_id: string;
      /**
       * Kind
       * @default doc
       * @constant
       */
      kind?: "doc";
      /** Relevance */
      relevance?: number | null;
      /** Source Id */
      source_id: string;
    };
    /**
     * EffortLevel
     * @description How much work a strategy is. Three levels, like every other scale here.
     * @enum {string}
     */
    EffortLevel: "low" | "medium" | "high";
    /**
     * ErrorCode
     * @enum {string}
     */
    ErrorCode: "invalid_repo_url" | "local_path_forbidden" | "repo_unavailable" | "repo_too_large" | "dependency_not_found" | "version_invalid" | "kb_unavailable" | "llm_unavailable" | "llm_rate_limited" | "thread_not_found" | "thread_not_awaiting_input" | "invalid_decision" | "internal";
    /**
     * ErrorResponse
     * @description The body of every non-2xx response from this API.
     *
     * One shape for every failure, so a client's error handling is written once.
     * The status code carries the class of problem; this carries what to say.
     */
    ErrorResponse: {
      error: components["schemas"]["ApiError"];
    };
    /**
     * FinalReport
     * @description Everything the run established, assembled once by `finalize`.
     *
     * A single object rather than a set of channels the API re-reads, because
     * the report is what a reader is handed and it has to be internally
     * consistent: the usage summary, the risk verdict and the plan all come from
     * one moment in the run's state. `finalize` is a pure function over that
     * state, so building it twice from the same checkpoint gives the same
     * report.
     *
     * There is deliberately **no status field**. Spec 6.5: status is computed
     * from the checkpoint plus the run registry, and a stored copy would drift
     * from reality on crash -- which is the very case `ORPHANED` exists for.
     * `COMPLETED` versus `COMPLETED_WITH_WARNINGS` is derivable from
     * `validation.passed`, so storing it would add nothing but a way to
     * disagree.
     */
    FinalReport: {
      /**
       * Affected Files
       * @default []
       */
      affected_files?: components["schemas"]["AffectedFile"][];
      /**
       * Agent Trace
       * @default []
       */
      agent_trace?: components["schemas"]["TraceEvent"][];
      /**
       * Breaking Changes
       * @default []
       */
      breaking_changes?: components["schemas"]["BreakingChange"][];
      /** Commit Sha */
      commit_sha: string | null;
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string;
      /**
       * Completed With Warnings
       * @description Whether validation failed after its one repair attempt.
       *
       * A `@computed_field` because the API's status ladder and the report
       * header both read it; see `ValidationReport.passed` for why derived
       * values that reach the client must be serialised rather than left as
       * bare properties.
       *
       * Derived here rather than stored so that the report and the status
       * cannot disagree -- see the class docstring. A report with no
       * validation at all is *not* "with warnings": the run did not get far
       * enough to produce a plan, which is a different and more visible
       * condition already carried by `migration_plan` being `None`.
       */
      completed_with_warnings: boolean;
      constraints: components["schemas"]["UserConstraints"];
      dependency: components["schemas"]["DependencySpec"];
      /**
       * Errors
       * @default []
       */
      errors?: string[];
      /**
       * Human Decisions
       * @default []
       */
      human_decisions?: components["schemas"]["HumanDecision"][];
      migration_plan?: components["schemas"]["MigrationPlan"] | null;
      rag_context?: components["schemas"]["RagContext"] | null;
      repo_analysis: components["schemas"]["RepoAnalysis"] | null;
      /** Repo Ref */
      repo_ref: components["schemas"]["RemoteRepoRef"] | components["schemas"]["LocalRepoRef"];
      risk_analysis?: components["schemas"]["RiskAnalysis"] | null;
      /** Thread Id */
      thread_id: string;
      usage: components["schemas"]["UsageSummary"];
      validation?: components["schemas"]["ValidationReport"] | null;
      /**
       * Version Discrepancy
       * @description `(stated, detected)` when the two disagree, else `None`.
       *
       * The rule itself is `RepoAnalysis.version_discrepancy`, which takes
       * the stated version as an argument because the analysis record does
       * not carry it -- the analyzer is told a dependency name, not what the
       * user believed its version to be. That makes it a method rather than a
       * field, and a method reaches no client: `model_dump()` does not call
       * it, so the one place in the product that knows the user's stated
       * version disagreed with the manifest was invisible to the report that
       * is supposed to say so (`docs/ui/READINESS.md` 3.9).
       *
       * `FinalReport` is the only model holding both halves, so this is where
       * the rule becomes visible. It delegates rather than reimplements --
       * the comparison, including the strip of raw caller input, stays in one
       * place.
       *
       * A `@computed_field` for the reason Phase 9 recorded against the four
       * it converted: a derived value the frontend cannot see is one the
       * frontend re-derives, which is a second implementation of the rule in
       * a language that cannot check it against this one.
       */
      version_discrepancy: [string, string] | null;
    };
    /** HealthChecks */
    HealthChecks: {
      /** Checkpoint Dir */
      checkpoint_dir: boolean;
      /** Chroma Dir */
      chroma_dir: boolean;
      /** Llm Configured */
      llm_configured: boolean;
    };
    /** HealthResponse */
    HealthResponse: {
      checks: components["schemas"]["HealthChecks"];
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
      /** Version */
      version: string;
    };
    /**
     * HumanDecision
     * @description One answered question. Validated from untrusted resume input.
     */
    HumanDecision: {
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string;
      /** Question Id */
      question_id: string;
      /** Rationale */
      rationale?: string | null;
      /** Selected Option Id */
      selected_option_id: string;
    };
    /**
     * InterruptPayload
     * @description Everything a person needs to answer one question without watching the run.
     */
    InterruptPayload: {
      /** Consequences If Unanswered */
      consequences_if_unanswered: string;
      /** Evidence */
      evidence: (components["schemas"]["RepoEvidence"] | components["schemas"]["DocEvidence"] | components["schemas"]["ConstraintEvidence"])[];
      kind: components["schemas"]["DecisionKind"];
      /** Options */
      options: components["schemas"]["DecisionOption"][];
      /** Question */
      question: string;
      /** Question Id */
      question_id: string;
      /** Reason */
      reason: string;
      /** Recommendation Id */
      recommendation_id?: string | null;
      /** Validation Error */
      validation_error?: string | null;
    };
    /**
     * LanguageShare
     * @description One language's share of the repository's recognised source files.
     *
     * Defined here in `models/`, not in `services/analysis/layout.py` where it is
     * produced: `RepoAnalysis.languages` is typed as a tuple of these, and
     * `models/` must never import `services/` (CLAUDE.md rule 16).
     */
    LanguageShare: {
      /** File Count */
      file_count: number;
      /** Language */
      language: string;
      /** Share */
      share: number;
    };
    /** LocalRepoRef */
    LocalRepoRef: {
      /**
       * Kind
       * @default local
       * @constant
       */
      kind?: "local";
      /** Path */
      path: string;
    };
    /** Manifest */
    Manifest: {
      /** Declared Specifier */
      declared_specifier?: string | null;
      kind: components["schemas"]["ManifestKind"];
      /** Path */
      path: string;
    };
    /**
     * ManifestKind
     * @enum {string}
     */
    ManifestKind: "pyproject" | "requirements" | "poetry_lock" | "uv_lock" | "pipfile_lock";
    /**
     * MigrationPlan
     * @description The plan. Ordered steps, the strategy behind them, and what was left out.
     */
    MigrationPlan: {
      /**
       * Human Decisions Applied
       * @default []
       */
      human_decisions_applied?: components["schemas"]["DecisionApplication"][];
      /**
       * Mitigations
       * @default []
       */
      mitigations?: string[];
      /**
       * Steps
       * @default []
       */
      steps?: components["schemas"]["MigrationStep"][];
      strategy_id: components["schemas"]["StrategyId"];
      /** Summary */
      summary: string;
      /**
       * Unaddressed With Reason
       * @default []
       */
      unaddressed_with_reason?: components["schemas"]["UnaddressedFile"][];
    };
    /**
     * MigrationStep
     * @description One piece of work, with something behind it.
     */
    MigrationStep: {
      /** Description */
      description: string;
      /**
       * Files
       * @default []
       */
      files?: string[];
      /** Order */
      order: number;
      /**
       * Rationale Evidence
       * @default []
       */
      rationale_evidence?: (components["schemas"]["RepoEvidence"] | components["schemas"]["DocEvidence"] | components["schemas"]["ConstraintEvidence"])[];
      /**
       * Requires Downtime
       * @default false
       */
      requires_downtime?: boolean;
      /** Title */
      title: string;
      /** Validation */
      validation?: string | null;
    };
    /**
     * ModelUsage
     * @description Usage attributed to one model.
     */
    ModelUsage: {
      /** Calls */
      calls: number;
      /** Cost Usd */
      cost_usd?: number | null;
      /** Input Tokens */
      input_tokens: number;
      /** Model */
      model: string;
      /** Output Tokens */
      output_tokens: number;
    };
    /**
     * NodeUsage
     * @description Usage attributed to one graph node.
     *
     * Kept because "where did the tokens actually go" is the second question a
     * developer asks (§9.4), and answering it from the call list afterwards is
     * impossible once the calls have been summed away.
     */
    NodeUsage: {
      /** Calls */
      calls: number;
      /** Cost Usd */
      cost_usd?: number | null;
      /** Input Tokens */
      input_tokens: number;
      /** Node */
      node: string;
      /** Output Tokens */
      output_tokens: number;
    };
    /**
     * RagContext
     * @description What the retrieval loop concluded, as the rest of the graph reads it.
     *
     * Spec 8.1 turns `evidence_available` into a hard confidence ceiling, which
     * is why it is **derived from the source count** rather than stored: a
     * stored flag is exactly the field a node under time pressure sets to
     * `True` beside an empty evidence list, and the ceiling would then never
     * engage. Absent evidence must not be able to produce a confident answer,
     * and the cheapest way to guarantee that is to make the flag uncomputable
     * from anything but the count.
     */
    RagContext: {
      /**
       * Evidence Available
       * @description Whether anything was retrieved at all. See the class docstring.
       *
       * `@computed_field`, so it appears in `model_dump()` and therefore in
       * the API response: this is the flag the report header renders beside
       * the confidence figure, and a frontend that could not see it would
       * re-derive it from a source count it also has to be given.
       */
      evidence_available: boolean;
      /** Iterations */
      iterations: number;
      /** Sources Considered */
      sources_considered: number;
      stop_reason: components["schemas"]["RagStopReason"];
      /** Sufficient */
      sufficient: boolean;
      /**
       * Unknowns
       * @default []
       */
      unknowns?: string[];
    };
    /**
     * RagStopReason
     * @description Why the retrieval loop stopped.
     *
     * Spec 7.3 bounds the loop three ways and skips it entirely a fourth, and
     * the four outcomes are not interchangeable: `SUFFICIENT` says the evidence
     * answered the question, `ITERATION_LIMIT` says we ran out of budget while
     * still short, `NOT_NECESSARY` says there was nothing to ask about, and
     * `KB_UNAVAILABLE` says we could not ask at all. Collapsing any two of them
     * would let a run that found nothing read like a run that needed nothing.
     * @enum {string}
     */
    RagStopReason: "sufficient" | "iteration_limit" | "not_necessary" | "kb_unavailable";
    /** RemoteRepoRef */
    RemoteRepoRef: {
      /**
       * Kind
       * @default remote
       * @constant
       */
      kind?: "remote";
      /** Url */
      url: string;
    };
    /** RepoAnalysis */
    RepoAnalysis: {
      /**
       * Affected Files
       * @default []
       */
      affected_files?: components["schemas"]["AffectedFile"][];
      /** Analyzed Files */
      analyzed_files: number;
      /**
       * Commit Records
       * @default []
       */
      commit_records?: components["schemas"]["CommitRecord"][];
      /** Commit Sha */
      commit_sha: string | null;
      /**
       * Confidence Reducers
       * @default []
       */
      confidence_reducers?: string[];
      detected_version: components["schemas"]["DetectedVersion"] | null;
      /**
       * Languages
       * @default []
       */
      languages?: components["schemas"]["LanguageShare"][];
      /**
       * Manifests
       * @default []
       */
      manifests?: components["schemas"]["Manifest"][];
      /**
       * Skipped Files
       * @default []
       */
      skipped_files?: components["schemas"]["SkippedFile"][];
      symbol_inventory: components["schemas"]["SymbolInventory"];
      /**
       * Test Paths
       * @default []
       */
      test_paths?: string[];
      /** Total Python Files */
      total_python_files: number;
    };
    /**
     * RepoEvidence
     * @description A specific line of the analyzed repository.
     */
    RepoEvidence: {
      /** File */
      file: string;
      /**
       * Kind
       * @default repo
       * @constant
       */
      kind?: "repo";
      /** Line */
      line: number;
      /** Snippet */
      snippet?: string | null;
    };
    /**
     * RepoInput
     * @description Where the repository is. Exactly one of `url` or `path`.
     *
     * Two nullable fields with a validator rather than a discriminated union,
     * because this is the shape a form posts: a UI with a radio button and two
     * text inputs sends the one the user filled in, and requiring a `kind`
     * discriminator alongside would be asking the client to restate what the
     * populated field already says.
     */
    RepoInput: {
      /** Path */
      path?: string | null;
      /** Url */
      url?: string | null;
    };
    /**
     * ResumeRequest
     * @description Continue a run.
     *
     * `decision` is optional, and its absence means something specific rather
     * than nothing: it is how an `ORPHANED` run -- one whose checkpoint survived
     * a restart its task did not -- is picked back up. A run awaiting a human
     * needs an answer; a run that lost its process needs only to be driven
     * again, and asking the client to invent a decision for it would be asking
     * for a lie.
     */
    ResumeRequest: {
      decision?: components["schemas"]["DecisionInput"] | null;
      /** Thread Id */
      thread_id: string;
    };
    /**
     * RiskAnalysis
     * @description The risk verdict. See the module docstring for what it refuses.
     */
    RiskAnalysis: {
      aggregate_risk: components["schemas"]["RiskLevel"];
      clamp_floor?: components["schemas"]["RiskLevel"] | null;
      /** Confidence */
      confidence: number;
      /**
       * Confidence Ceilings
       * @default []
       */
      confidence_ceilings?: components["schemas"]["ConfidenceCeiling"][];
      /**
       * Factors
       * @default []
       */
      factors?: components["schemas"]["RiskFactor"][];
      overall_risk: components["schemas"]["RiskLevel"];
      /**
       * Qualitative Notes
       * @default []
       */
      qualitative_notes?: string[];
      /** Summary */
      summary: string;
    };
    /**
     * RiskCategory
     * @enum {string}
     */
    RiskCategory: "breaking_change_exposure" | "blast_radius" | "test_coverage_of_affected" | "churn_on_affected" | "analysis_coverage" | "evidence_coverage" | "constraint_pressure";
    /**
     * RiskFactor
     * @description One dimension of risk. `evidence` must be non-empty.
     */
    RiskFactor: {
      category: components["schemas"]["RiskCategory"];
      /** Detail */
      detail: string;
      /** Evidence */
      evidence: (components["schemas"]["RepoEvidence"] | components["schemas"]["DocEvidence"] | components["schemas"]["ConstraintEvidence"])[];
      /** Id */
      id: string;
      level: components["schemas"]["RiskLevel"];
      /** Name */
      name: string;
      /** Weight */
      weight: number;
    };
    /**
     * RiskLevel
     * @enum {string}
     */
    RiskLevel: "low" | "medium" | "high";
    /**
     * RunSnapshot
     * @description One response model for every state a run can be in. Spec 9.1.
     */
    RunSnapshot: {
      /**
       * Affected Files
       * @default []
       */
      affected_files?: components["schemas"]["AffectedFile"][];
      /**
       * Breaking Changes
       * @default []
       */
      breaking_changes?: components["schemas"]["BreakingChange"][];
      /**
       * Completed Steps
       * @default []
       */
      completed_steps?: string[];
      /** Current Step */
      current_step?: string | null;
      /**
       * Errors
       * @default []
       */
      errors?: components["schemas"]["ApiError"][];
      final_report?: components["schemas"]["FinalReport"] | null;
      /**
       * Human Decisions
       * @default []
       */
      human_decisions?: components["schemas"]["HumanDecision"][];
      migration_plan?: components["schemas"]["MigrationPlan"] | null;
      pending_decision?: components["schemas"]["InterruptPayload"] | null;
      rag_context?: components["schemas"]["RagContext"] | null;
      /**
       * Retrieved Sources
       * @default []
       */
      retrieved_sources?: components["schemas"]["SourceRef"][];
      risk_analysis?: components["schemas"]["RiskAnalysis"] | null;
      status: components["schemas"]["RunStatus"];
      /** Thread Id */
      thread_id: string;
      /**
       * Trace
       * @default []
       */
      trace?: components["schemas"]["TraceEvent"][];
      usage: components["schemas"]["UsageView"];
      validation?: components["schemas"]["ValidationReport"] | null;
    };
    /**
     * RunStatus
     * @description Spec 9.2's run states. Derived from the checkpoint plus the registry.
     *
     * Never stored (spec 6.5): a stored status drifts from reality on crash,
     * which is precisely the case `ORPHANED` exists to describe -- and a field
     * written by the process that then died would say `RUNNING` forever.
     *
     * `QUEUED` and `ORPHANED` are real states rather than politeness.
     * `QUEUED` is what a run beyond the concurrency cap actually is, and
     * reporting it as `RUNNING` would be a lie about work that has not started.
     * `ORPHANED` is a run whose checkpoint survived a restart that its task did
     * not; the alternative is a spinner that never resolves.
     * @enum {string}
     */
    RunStatus: "queued" | "running" | "awaiting_human" | "completed" | "completed_with_warnings" | "failed" | "orphaned";
    /**
     * Severity
     * @enum {string}
     */
    Severity: "low" | "medium" | "high";
    /** SkippedFile */
    SkippedFile: {
      /** Path */
      path: string;
      /** Reason */
      reason: string;
    };
    /**
     * SourceRef
     * @description A resolvable pointer into the knowledge base.
     */
    SourceRef: {
      /** Chunk Id */
      chunk_id: string;
      /** Relevance */
      relevance: number;
      /** Source Id */
      source_id: string;
      source_type: components["schemas"]["SourceType"];
      /** Title */
      title: string;
      /** Url Or Reference */
      url_or_reference: string;
    };
    /**
     * SourceType
     * @enum {string}
     */
    SourceType: "migration_guide" | "changelog" | "adr" | "upgrade_report" | "compat_note";
    /**
     * StartResponse
     * @description 202 from both `start` and `resume`: accepted, not finished.
     */
    StartResponse: {
      /** Poll Url */
      poll_url: string;
      status: components["schemas"]["RunStatus"];
      /** Thread Id */
      thread_id: string;
    };
    /** StartRunRequest */
    StartRunRequest: {
      constraints?: components["schemas"]["UserConstraints"];
      dependency: components["schemas"]["DependencyInput"];
      repo: components["schemas"]["RepoInput"];
    };
    /**
     * StrategyId
     * @description The candidate migration strategies of spec 8.2.
     *
     * A closed enum rather than free strings, because `MigrationPlan.strategy_id`
     * is what the decision-flip test compares: resuming the same checkpoint with
     * the opposite option must yield a *different* strategy, and comparing two
     * free-form strings would pass on a typo.
     * @enum {string}
     */
    StrategyId: "direct_migration" | "compatibility_layer" | "staged_rollout";
    /** SymbolInventory */
    SymbolInventory: {
      /**
       * Entries
       * @default []
       */
      entries?: components["schemas"]["SymbolStat"][];
    };
    /** SymbolStat */
    SymbolStat: {
      confidence: components["schemas"]["Confidence"];
      /** Count */
      count: number;
      /** Files */
      files: string[];
      /** Symbol */
      symbol: string;
    };
    /**
     * TraceEvent
     * @description One observable thing the run did.
     */
    TraceEvent: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Detail */
      detail?: string | null;
      /** Event Id */
      event_id: string;
      kind: components["schemas"]["TraceEventKind"];
      /** Node */
      node: string;
      /** Summary */
      summary: string;
    };
    /**
     * TraceEventKind
     * @description What the agent trace is allowed to report.
     *
     * CLAUDE.md rule 26 draws the line: the trace shows *observable* events --
     * node boundaries, queries issued, sources retrieved and selected,
     * decisions, validation outcomes -- and never internal prompts or private
     * reasoning. Enumerating the kinds is what makes that rule checkable:
     * adding one is a deliberate decision about what the product exposes rather
     * than an incidental addition somewhere in a node.
     * @enum {string}
     */
    TraceEventKind: "node_started" | "node_completed" | "query_issued" | "sources_retrieved" | "sources_selected" | "retrieval_evaluated" | "agent_decision" | "decision_required" | "decision_applied" | "validation_outcome" | "error_recorded";
    /**
     * UnaddressedFile
     * @description A file the plan does not change, and why not.
     *
     * The alternative to this model is silence, and silence is what makes a
     * partial plan read as a complete one. Spec 8.4's eighth check requires
     * every high-confidence affected file to be either addressed by a step or
     * named here -- so "we did not cover this" is a thing the report says out
     * loud rather than a gap the reader has to find by comparing two lists.
     */
    UnaddressedFile: {
      /** Path */
      path: string;
      /** Reason */
      reason: string;
    };
    /**
     * UsageKind
     * @enum {string}
     */
    UsageKind: "import" | "model_definition" | "decorator" | "nested_config" | "optional_field" | "method_call";
    /** UsageSite */
    UsageSite: {
      /** Column */
      column: number;
      confidence: components["schemas"]["Confidence"];
      /** File */
      file: string;
      kind: components["schemas"]["UsageKind"];
      /** Line */
      line: number;
      /** Snippet */
      snippet?: string | null;
      /** Symbol */
      symbol: string;
    };
    /**
     * UsageSummary
     * @description Totals derived from `llm_calls`. Never stored -- see the module docstring.
     */
    UsageSummary: {
      /**
       * By Model
       * @default []
       */
      by_model?: components["schemas"]["ModelUsage"][];
      /**
       * By Node
       * @default []
       */
      by_node?: components["schemas"]["NodeUsage"][];
      /** Calls */
      calls: number;
      /**
       * Estimated
       * @default false
       */
      estimated?: boolean;
      /** Estimated Cost Usd */
      estimated_cost_usd?: number | null;
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      /**
       * Pricing Complete
       * @default true
       */
      pricing_complete?: boolean;
    };
    /**
     * UsageView
     * @description Usage, with the two flags that stop a total being misread.
     *
     * `estimated` says at least one token count came from a local tokenizer.
     * `pricing_complete` says every counted call had a price -- when it is false
     * the cost is a **lower bound**, and this flag is the only thing that says
     * so. Both are surfaced at the top level of the API rather than left inside
     * the summary, because a UI that has to dig for them is a UI that will print
     * the number alone.
     */
    UsageView: {
      /** By Model */
      by_model: [string, number][];
      /** By Node */
      by_node: [string, number][];
      /** Calls */
      calls: number;
      /** Estimated */
      estimated: boolean;
      /** Estimated Cost Usd */
      estimated_cost_usd: number | null;
      /** Input Tokens */
      input_tokens: number;
      /** Output Tokens */
      output_tokens: number;
      /** Pricing Complete */
      pricing_complete: boolean;
      /** Total Tokens */
      total_tokens: number;
    };
    /**
     * UserConstraints
     * @description Migration constraints. Defaults are permissive so an omitted
     * constraint never silently tightens the recommendation.
     */
    UserConstraints: {
      /** Deadline */
      deadline?: string | null;
      /**
       * Minimize Effort
       * @default false
       */
      minimize_effort?: boolean;
      /** @default medium */
      risk_tolerance?: components["schemas"]["RiskLevel"];
      /**
       * Zero Downtime
       * @default false
       */
      zero_downtime?: boolean;
    };
    /**
     * ValidationCheckId
     * @description Spec 8.4's ten deterministic checks, named.
     *
     * An enum rather than free strings because `ValidationReport` is rendered in
     * the UI and quoted in the final report: a check whose id was a typo would
     * render as a check that passed silently, since nothing would look for it.
     * The membership of this enum is what `test_every_check_runs_on_every_plan`
     * asserts against the validator's output, so a check added here without an
     * implementation fails immediately.
     * @enum {string}
     */
    ValidationCheckId: "sources_resolve" | "repo_evidence_resolves" | "step_files_exist" | "risk_factors_cite_evidence" | "risk_clamp_holds" | "confidence_ceilings_hold" | "plan_is_ordered" | "affected_files_addressed" | "decisions_applied" | "zero_downtime_respected";
    /**
     * ValidationOutcome
     * @description One check, its verdict, and what failed it.
     */
    ValidationOutcome: {
      check_id: components["schemas"]["ValidationCheckId"];
      /** Detail */
      detail: string;
      /**
       * Offenders
       * @default []
       */
      offenders?: string[];
      /** Passed */
      passed: boolean;
    };
    /**
     * ValidationReport
     * @description Every check's outcome for one attempt at the plan.
     */
    ValidationReport: {
      /** Attempt */
      attempt: number;
      /** Outcomes */
      outcomes: components["schemas"]["ValidationOutcome"][];
      /**
       * Passed
       * @description Derived, never stored (CLAUDE.md rule 21). A stored verdict beside
       * a list of failures is the one shape that can lie about itself, and
       * `COMPLETED_WITH_WARNINGS` is exactly where the two would be tempted to
       * disagree.
       *
       * `@computed_field` rather than a bare property, for the same reason
       * `AffectedFile.symbols` is one: it has to appear in `model_dump()`, and
       * therefore in the API response and the generated TypeScript. A derived
       * value the frontend cannot see is one the frontend re-derives, which is
       * a second implementation of the rule in a language that cannot check
       * it against this one.
       */
      passed: boolean;
    };
    /**
     * VersionConfidence
     * @enum {string}
     */
    VersionConfidence: "exact" | "range";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Resume */
  resume_api_agent_resume_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResumeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": components["schemas"]["StartResponse"];
        };
      };
      /** @description No run with that id */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The run is not waiting for input */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The request could not be accepted */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Start */
  start_api_agent_start_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": components["schemas"]["StartResponse"];
        };
      };
      /** @description No run with that id */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The run is not waiting for input */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The request could not be accepted */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Get Status
   * @description The one response shape, in every state.
   *
   * A thread nobody started is a **404** rather than an empty snapshot:
   * measured against the pinned LangGraph, `aget_state` answers for an unknown
   * id with a perfectly ordinary snapshot, so an endpoint that did not check
   * would return 200 and a blank report for any string a client sent.
   */
  get_status_api_agent_status__thread_id__get: {
    parameters: {
      path: {
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunSnapshot"];
        };
      };
      /** @description No run with that id */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The run is not waiting for input */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description The request could not be accepted */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * Health
   * @description Liveness, local-store readiness, and model-provider configuration.
   *
   * `status` is derived from `checks` by `_derive_status` and is never
   * asserted independently of them. It previously was: the endpoint returned
   * a hardcoded `"ok"` alongside whatever the checks happened to say, so a
   * 200 with `"ok"` was demonstrated while both store checks were false --
   * and the frontend rendered that as a green tick. A health endpoint that
   * cannot be wrong about its own checks is the whole point of this route.
   *
   * Every check is a cheap local read: two filesystem stats and one look at
   * already-loaded settings. Nothing here is reported as unknown because
   * nothing here is expensive enough to need to be. In particular this
   * deliberately does **not** open the Chroma store, connect to the
   * checkpointer database, or call the model provider -- a health probe must not cost
   * money or inherit third-party latency, so what it reports is the
   * readiness of the store *locations* and the presence of a key, which is
   * exactly what the field names say and no more.
   *
   * `llm_configured` counts toward `status` like any other check. A
   * missing key means the agent cannot do its job, so reporting `"ok"`
   * without one would be the same class of false claim in a smaller font.
   */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
