/**
 * The seven-factor table -- the product's core honesty artifact.
 *
 * Each factor's level comes from a documented threshold table without an LLM
 * (rule 19), each carries evidence with `min_length=1`, and each row can be
 * opened to see exactly what it cited. That combination is the reason a
 * developer should believe the verdict, and it is what an earlier design
 * replaced with a letter grade, a score out of ten and a donut chart.
 *
 * Every factor is shown, not only the alarming ones: a table that hid its low
 * rows would be a table whose absences the reader cannot interpret.
 */

import { useState } from "react";

import type { RiskAnalysis, RiskFactor } from "../../api/types";
import { describeEvidenceRef, evidenceRefKey } from "../../derive/evidence";
import { EmptyState, LevelBadge, Mono, Panel } from "../ui";

/**
 * The single renderer for an `EvidenceRef[]` (ruling T11b) -- used here and
 * by `HumanReviewPanel`, so the product has exactly one way to render a
 * citation rather than two free to disagree.
 *
 * The formatting itself (`describeEvidenceRef`) lives in `derive/` because it
 * is a pure function of the ref; this component's own job is the list
 * chrome and the one thing the formatter cannot show -- a repo ref's
 * snippet, when it carries one.
 */
export function EvidenceRefList({ refs }: { refs: RiskFactor["evidence"] }) {
  return (
    <ul className="mt-2 space-y-1 border-l border-edge pl-3">
      {refs.map((ref) => (
        <li key={evidenceRefKey(ref)} className="text-xs text-ink-muted">
          <Mono>{describeEvidenceRef(ref)}</Mono>
          {/* `snippet` is optional and nullable on `RepoEvidence`; loose
              (`!= null`), not strict, or the common case of no snippet sent
              would render an empty `<pre>` (ruling N1). */}
          {"file" in ref && ref.snippet != null && (
            <pre className="mt-1 overflow-x-auto rounded bg-surface-sunken p-2 font-mono text-[12px] text-ink-muted">
              {ref.snippet}
            </pre>
          )}
        </li>
      ))}
    </ul>
  );
}

function FactorRow({ factor }: { factor: RiskFactor }) {
  const [open, setOpen] = useState(false);

  return (
    <li className="border-b border-edge py-3 last:border-0">
      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <LevelBadge level={factor.level} />
        <span className="text-sm font-medium">{factor.name}</span>
        <span className="text-[11px] text-ink-faint">weight {factor.weight.toFixed(2)}</span>
        <button
          type="button"
          onClick={() => setOpen(!open)}
          aria-expanded={open}
          className="ml-auto text-[11px] text-ink-muted underline hover:text-ink"
        >
          {factor.evidence.length} evidence {factor.evidence.length === 1 ? "ref" : "refs"}
        </button>
      </div>
      <p className="mt-1 text-sm text-ink-muted">{factor.detail}</p>
      {open && <EvidenceRefList refs={factor.evidence} />}
    </li>
  );
}

export function RiskFactorsTab({ analysis }: { analysis: RiskAnalysis | null }) {
  if (analysis === null) {
    return (
      <Panel title="Risk factors">
        <EmptyState>No risk assessment was produced for this run.</EmptyState>
      </Panel>
    );
  }

  // `factors` is optional in the generated type only because every Pydantic
  // field carries a default -- `assess_risk` always populates it. Resolved
  // once here rather than at each use (ruling T10b).
  const factors = analysis.factors ?? [];

  return (
    <Panel title="Risk factors">
      <p className="mb-3 text-xs text-ink-faint">
        Every level below is computed from a documented threshold table, not generated by the
        model. Open a row to see what it cited.
      </p>
      {factors.length === 0 ? (
        <EmptyState>No factors were measured.</EmptyState>
      ) : (
        <ul>
          {factors.map((factor) => (
            <FactorRow key={factor.id} factor={factor} />
          ))}
        </ul>
      )}
    </Panel>
  );
}
