/**
 * The seven-factor table -- the product's core honesty artifact.
 *
 * Each factor's level comes from a documented threshold table without an LLM
 * (rule 19), each carries evidence with `min_length=1`, and each row can be
 * opened to see exactly what it cited. That combination is the reason a
 * developer should believe the verdict, and it is what an earlier design
 * replaced with a letter grade, a score out of ten and a donut chart.
 *
 * Every factor is shown, not only the alarming ones: a table that hid its low
 * rows would be a table whose absences the reader cannot interpret.
 */

import { useState } from "react";

import type { RiskAnalysis, RiskFactor } from "../../api/types";
import { EvidenceRefList } from "../EvidenceRefList";
import { EmptyState, LevelBadge, Panel } from "../ui";

function FactorRow({ factor }: { factor: RiskFactor }) {
  const [open, setOpen] = useState(false);

  return (
    <li className="border-b border-edge py-3 last:border-0">
      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <LevelBadge level={factor.level} />
        <span className="text-sm font-medium">{factor.name}</span>
        <span className="text-[11px] text-ink-faint">weight {factor.weight.toFixed(2)}</span>
        <button
          type="button"
          onClick={() => setOpen(!open)}
          aria-expanded={open}
          className="ml-auto text-[11px] text-ink-muted underline hover:text-ink"
        >
          {factor.evidence.length} evidence {factor.evidence.length === 1 ? "ref" : "refs"}
        </button>
      </div>
      <p className="mt-1 text-sm text-ink-muted">{factor.detail}</p>
      {open && <EvidenceRefList refs={factor.evidence} />}
    </li>
  );
}

export function RiskFactorsTab({ analysis }: { analysis: RiskAnalysis | null }) {
  if (analysis === null) {
    return (
      <Panel title="Risk factors">
        <EmptyState>No risk assessment was produced for this run.</EmptyState>
      </Panel>
    );
  }

  // `factors` is optional in the generated type only because every Pydantic
  // field carries a default -- `assess_risk` always populates it. Resolved
  // once here rather than at each use (ruling T10b).
  const factors = analysis.factors ?? [];

  return (
    <Panel title="Risk factors">
      <p className="mb-3 text-xs text-ink-faint">
        Every level below is computed from a documented threshold table, not generated by the
        model. Open a row to see what it cited.
      </p>
      {factors.length === 0 ? (
        <EmptyState>No factors were measured.</EmptyState>
      ) : (
        <ul>
          {factors.map((factor) => (
            <FactorRow key={factor.id} factor={factor} />
          ))}
        </ul>
      )}
    </Panel>
  );
}
